### ISSUE TITLE
Additional attributes for Phone object

### ISSUE THREAD

**Issue by NeilMcKechnie** [openreferral/specification#126]
The Phone object currently has "type" and "department" fields but it could benefit from new fields: name and description.

Contrived example:
Number: 800-123-4567
Type: Tollfree
Name: Veterans for Peace Hotline
Description: Operates 24/7 to help counsel veterans with PTSD and their families/supporters

**Comment by klambacher** [comment]
We also keep a separate element for option (e.g. "use option 1 for legal services") which I know is less common, but we need to accommodate the data because it is being kept.

**Comment by timgdavies** [comment]
@klambacher Would "use option 1 for legal services" be separate from the value of the existing ```extension``` field?

@NeilMcKechnie I'm wondering to what extent (a) the description lives at a service level, and (b) whether systems would be likely to display this information? 

For example, a 24/7 helpline feels like a distinct (virtual location) service of an organisation, rather than something that should be described only at the level of one of the possible phone numbers of a service.

**Comment by NeilMcKechnie** [comment]
Hi @timgdavies , a single service can have multiple different phone lines and a description field helps make that more clear. Since each phone number is well structured in its own field (and not "OR'ed together in just one field), consuming applications can more reliably do things like tap-to-call, Skype integrations, and so on. 

To keep going with my contrived but relevant example:

Number: 800-123-4567
Type: Tollfree
Name: Veterans for Peace Hotline
Description: Operates 24/7 to help counsel veterans with PTSD and their families/supporters

Number: +1-415-777-8888
Type: Local
Name: Veterans for Peace Hotline
Description: Operates 24/7. If calling from overseas and tollfree is not available, you can use this number instead.

Number: 415-999-8888
Type: Administrative
Name: Veterans for Peace Hotline
Description: Operates Monday-Friday, 9am - 4pm Pacific Standard Time. For job applications, volunteer opportunities, and other administrative inquiries for this service, please call this phone number. If after hours, leave a voicemail for a call back the next business day.

**Comment by timgdavies** [comment]
Thanks @NeilMcKechnie 

At the moment phone contains:

* Number
* Extension
* Type (a codelist of ["text","voice","fax","cell","video","pager","textphone"] based on RFC6350) 
* Department

For every field we include, we need to think about whether or not consuming applications are likely to display this information, as we certainly want to avoid the case where information is present in the data, but not given to the user (leading to them calling the wrong number etc.). 

This leaves me cautious about including new fields - but I wonder if a compromise would be to:

* Deprecate ```department``` (this would still exist as a property of ```contact``` - and contacts may have phone numbers and links to organisations and services);
* Add ```description``` in it's place;

I'm still a bit concerned that timing information might be better expressed (in terms of ensuring it reaches the eyes of users) either (a) in structured form in ```Regular_Schedule``` or ```Holiday_Schedule```; or (b) as part of the free text service description (e.g. 'Phone hotline operates Monday-Friday, 9am - 4pm Pacific Standard Time' on ```Service.description```) rather than in the phone number properties.

**Comment by NeilMcKechnie** [comment]
Thanks @timgdavies . I'm keen to hear if others have an opinion about this. But losing "department" to gain "description" is a great trade, in my opinion.
