### ISSUE TITLE
Open Data day 2017  -- tracking Open 211 success stories

### ISSUE THREAD

**Issue by kelfink** [openreferral/specification#134]
For the upcoming Open Data day tomorrow. I'd like to gather information about how each California (or any state's) county treats its 211 data, and how that affects the community at large. But I am still searching for metrics our volunteers can gather to show the benefits of publishing the data. 

Suggestions?

**Comment by greggish** [comment]
@kelfink I'd be happy to share some knowledge, and can make some introductions to folks in various capacities across the 2-1-1 network in California (although it's pretty late in the game for tomorrow). That said, it might be helpful to get a better sense of what you're looking for. 

I saw that @neilmckechnie responded in the other thread... and I'll be at Open Data Day in NYC tomorrow, where i could step aside to videochat in with folks in California if that can be helpful. Let me know!

**Comment by kelfink** [comment]
That's extremely kind, thanks.   I'd love to have a longer chat about sustainable import and update of data in Ohana and elsewhere.   For tomorrow, unfortunately I am only pitching now because I can't attend tomorrow's event.  SacSOS.org is loaded primarily with EBT data from https://github.com/SacHomeless/Hack4Sac/blob/master/data/federal_ebt_data.csv
and WIC data from https://chhs.data.ca.gov/Facilities-and-Services/Women-Infants-and-Children-WIC-Authorized-Vendors/x5nq-b49e

Ultimately, I wrote ruby scripts to generate approximate entities in Ohana, when we built the system.  And we can write more to update existing records, now that it's 2017.
If you want chat at a later time, when more members of our team can learn and discuss, that would be super.  Oh, and come chat with Code4Sac any time you're out here!

**Comment by NeilMcKechniePersonal** [comment]
hey @kelfink , I'm in the Bay Area but am planning a trip up to Sacramento soon. I'll reach out in case we can meet up while I am there.

Relatedly tomorrow I'm attending a Tech4Good hackathon in San Francisco. I'm not sure if it is associated with "Open Data Day" (is that a national thing?) but I'll ask.  http://usf4impact.org/tech4good/

Generally I would say the California 2-1-1's are open to experimenting with data sharing relationships with third parties. Greg or I could facilitate introductions.

**Comment by kelfink** [comment]
Nice!   Open Data Day is national (greggish is participating in NYC)  but I got notice late and have other plans.   Not sure how to push the 211 relationship issue, locally.  Our local agency has dragged their feet on it--but I think we have the necessary introductions.   My pitch to map openness of 211 systems is meant to point out the benefits of sharing--not shame them.  What I'm hoping for is some metric that a county can point to and say : Ooh, if our 211 system shared data openly, we'd have X.  X is good!  Maybe X is just 'other organizations innovating with this data'   but I can't point to that on a map so well.  

Swing by Code4Sac any Wednesday night.  We'd love to chat!
Kevin Fries

**Comment by joelrip** [comment]
@greggish and @NeilMcKechniePersonal, thanks for responding! I'll reiterate @kelfink 's offer to come up and talk to us any time. I think I mentioned in previous conversations that 2-1-1 Sacramento has been reticent to share information. In our most recent interaction (late 2016), they initially responded positively to trying to export some data in HSDS format, but balked when they learned it might go into another database.

But I think we've got several avenues we can use to approach them. Kevin's approach of showing what's possible when data is shared is probably the softest (but still very good) approach. A conversation involving the two of you would probably carry more weight. At the harder end, the Sacramento Mayor's office really wants this information released, and is prepared to start applying pressure (not that 2-1-1 Sacramento is directly beholden to the mayor).

Our Open Data Day event tomorrow (which is an international phenomenon, incidentally) will focus on people entering, uploading, cleaning, sharing, etc data. Absent 2-1-1 Sacramento data, people will be accumulating various data from other sources for the SacSOS project. But it would also be valuable if there were some 2-1-1 data from another nearby county (maybe one run by United Way?) that they could try importing. Is that within the realm of possibility?

**Comment by greggish** [comment]
@joelrip I enjoyed my time at Code for Sacramento a couple of years ago (when I briefed the WIC-it team), and I also had a chance to brief Joanne Werneke about all of these dynamics a year ago, so I'm glad to be finally back in touch.

To get access to quality data that's actively curated, I find these things to take time, trust-building, and a certain amount of cooperative negotiation. 

Often times when the conversation is framed around "can you give us data," 2-1-1 providers (typically underfunded nonprofits that spend a good portion of their budget maintaining that data) don't readily see how that is going to help anyone. Even something like simply exporting data comes with costs and liabilities that need to be justified. I certainly think 2-1-1s questions about "why?" are *answerable*, but I also recognize those answers might be less obvious than those of us in the civic tech world assume them to be. 

That's why I appreciate @kelfink's framing around demonstrating the benefits. This is still early days for opening 2-1-1 systems, so I don't know how many hard metrics we can offer. But we do have examples of benefits such as [Purple Binder's Open Referral API in Chicago](https://openreferral.org/open-referral-action-purple-binder-platform/) (which is supporting multiple third-party apps that would otherwise be duplicative and competitive) and the rapid, cheap development of new applications _in partnership with_ the 2-1-1 such as [what we're seeing in Oklahoma](https://openreferral.org/open-referral-in-oklahoma/).

I also have [this set of working hypotheses about prospective open data business models](https://docs.google.com/document/d/1vS6MBo9BtuyqjqYiCulieexS7B3vgl2s6OC1NHJPlJ8/edit#heading=h.sfzs9wnnw0fx), which I've already proposed to some key people at 2-1-1 Sacramento and elsewhere. If we were to have a conversation with iCarol, 2-1-1 Sac, and the Mayor's office, this is the framework I would bring to the table. 

In the near-term, with some careful engagement, I believe you all could at least get access to data about services provided by state and federal government... but unless Neil and his partners at United Way are ready to move on a dime, I doubt it's going to come today. Hope to be involved in more sustained conversations in the future.

**Comment by roughani** [comment]
So what's the next step? A one-pager that explains the benefits? A conference call? More reconnaissance? Regardless, it needs to be concise and simple. We're dealing with very busy people and making it easier for them to say no than yes. So how do we make it easy for them to say yes in a way that respects everyone's limited time and attention?

**Comment by greggish** [comment]
Good questions. On a statewide level, I know that Benetech is in dialogue with leadership of United Ways (statewide and Bay Area) and California government agencies, so I think by default we can loop back to them with such questions and/or suggestions. 

That said, in the meantime, I'd be happy to explore the local landscape a bit more with you if I can be helpful.

To your request for concise primers, I find that different stakeholders often benefit from different kinds of summaries. 

I have [this general purpose executive summary](https://docs.google.com/document/d/1xjXYN0zzUVWK3GdINP3erO-Jm0LUz75962SyRF0ggIA/edit), for starters. 

For 2-1-1s and other referral providers, I find that [the two-page 'open data business strategy' memo](https://docs.google.com/document/d/1vS6MBo9BtuyqjqYiCulieexS7B3vgl2s6OC1NHJPlJ8/edit#heading=h.sfzs9wnnw0fx) (with appendices) linked above is a decent starting point. 

For California stakeholders generally, I still have [this memo](https://docs.google.com/document/d/1AS-L9M1haTMIDSyC1yXnpS8XRyx6kW14wzSlw6lubxk/edit#heading=h.pbbc2hwg854b) which starts with a one-pager designed for government officials. 

All of these documents can benefit from updates and grooming -- so I welcome critical feedback that can help improve them. And if you identify a kind of stakeholder who might benefit from a different kind of entrance point, I'm happy to work on new documentation.

That said, this issue is inherently not-simple. (And this field is especially cluttered in part because so many previous attempts to simplify have resulted in insufficient solutions with attendant path dependencies and vested interests.) I think our objective should be to do whatever it takes to establish capacity for people to actually delve into the complexities, together, for sustained periods of time.
