### ISSUE TITLE
Generating ERD diagrams from JSON table schema

### ISSUE THREAD

**Issue by duncandewhurst** [openreferral/specification#147]
I have been looking into tools for generating an ERD diagram from the OpenReferral JSON table schema.

I came across [jts_erd](https://github.com/iburadempa/jts_erd/blob/master/jts_erd/jts_erd.py) which consumes an extended JSON table schema, generated from a PostgreSQL database, but I haven't yet been able to get this working with the OpenReferral schema.

The next avenue to investigate is tool to convert JSON table schema into a relational database, from which an ERD could be generated, but I would prefer to work directly with the JSON table schema if possible.

Please share thoughts or suggestions for any tools or libraries which might be useful.

Thanks!

**Comment by timgdavies** [comment]
@spilio has any of your exploration of data package tooling thrown up possibilities here?

**Comment by kinlane** [comment]
I'm working on a JSON schema for the Human Services Data Specification (HSDS), as well as for the surface area of the Human Service Data API (HDSA) -- my JSON schema chops aren't that sharp, so I'm still polishing and will share when ready.

Secondarily as part of my portal demo API that I'm keeping in alignment with the HSDS/A I will be publishing a MySQL script. I'll put on the list for translation for PostgreSQL on the working list.

**Comment by MaxWhitney** [comment]
Not directly responsive (not a solution to the JSON to ERD tool question),
but I drafted an ER diagram based on the Open Referral API v1.1 yaml.

A png of the draft is attached.

**Comment by kinlane** [comment]
Apologies misread question, and crossed with other -- clearing.

**Comment by timgdavies** [comment]
Thanks @MaxWhitney  

I don't think the attachments come through for GitHub comments via e-mail. Could you drag and drop it into an issue reply at https://github.com/openreferral/specification/issues/147 ?

Thanks!

**Comment by spilio** [comment]
@timgdavies A relational DDL generator could be an interesting feature within the context of the playground app.  @duncandewhurst I don't really understand the need of an ERD generator - although I come from the enterprise it sounds tool old-school to me :) - but since it's in your wish list, I could have a look and see if I can come up with something.  I'll create a couple of feature tickets in my project.  Nevertheless, if you need an interactive visualization at the API level, you can try out my [swagger.ed](https://chrome.google.com/webstore/detail/swaggered/kaggdmjacnelneophkagkdljffninnpd) Chrome extension and use it with @kinlane OpenAPI definition.

**Comment by MaxWhitney** [comment]
I attached the .png to my earlier message and have issued a pull request to include the diagram in a new 'er_diagram' folder in location openreferral/specification/

**Comment by timgdavies** [comment]
Belated thanks @MaxWhitney : this is now all merged in. 

Will look at ways to keep it updated in future.
