### ISSUE TITLE
regular_schedule.weekday is an Integer - what are the values?

### ISSUE THREAD

**Issue by NeilMcKechnie** [openreferral/specification#164]
The documentation lists it as an Integer but then does not say which day is assumed to be the start of the week, and if that day is 0 or 1. Please clarify in the documentation.

http://docs.openreferral.org/en/latest/reference/#regular_schedule

**Comment by timgdavies** [comment]
Good point. Looking at [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Week_dates):

> [D] is the weekday number, from 1 through 7, beginning with Monday and ending with Sunday.

so that would be the precedent I would think we would be following. Tagging this as a potential bug-fix, unless there are strong views that '0' (or Sunday) should be the first day - and systems that have implemented as such.

**Comment by rasmus-storjohann-PG** [comment]
This https://schema.org/openingHours might also be a way to handle schedule, see https://stackoverflow.com/a/27057779

**Comment by timgdavies** [comment]
I've pushed a fix on the 1.1.1 branch to clarify that 1 = Monday.

**Comment by Bjwebb** [comment]
Fix is in the live docs now http://docs.openreferral.org/en/latest/hsds/reference/#regular_schedule

More advanced ways of representing opening times is being discussed in https://github.com/openreferral/specification/issues/167
