### ISSUE TITLE
Build fails with `No module named 'sphinxcontrib.opendataservices'`

### ISSUE THREAD

**Issue by robredpath** [openreferral/specification#201]
When I tried to update the reqs to deal with a vuln notification, the build fails with:

`Could not import extension sphinxcontrib.opendataservices (exception: No module named 'sphinxcontrib.opendataservices')`

Would this be related to our recent updates to our Sphinx build stack @kindly @odscjames ?

**Comment by Bjwebb** [comment]
Turns out the problem was the dependency was missing from the requirements. It was in requirements.txt, but not requirements.in, so got overwritten when you tried to update.

I fixed this as part of starting to use pip-tools https://github.com/openreferral/specification/commit/d254fc4d9d5b6083a48ed92676f5b10a957c3521, and I've updated requirements https://github.com/openreferral/specification/commit/3d88ad84da53273948a2dfbdd3581d729fb7365e. (This is all in my working branch for the next release atm.).
