### ISSUE TITLE
ERD Diagram - text overlaps the box

### ISSUE THREAD

**Issue by ghost** [openreferral/specification#266]
On some computers, the ERD diagram appears like this:

![overlapping](https://user-images.githubusercontent.com/37832009/137158416-3fcd129e-31f5-4bf0-8444-51c42f7ad17b.png)

This is maybe because Graphhviz on the computer that builds it (so, in production this is a ReadTheDocs server) looks up the font that is set for the diagram and calculates the widths each box needs based on that. 

But if the computer the viewer uses does not have that font, the web browser will use another font. And that font might have a different width & spacing, and thus the overlap happens.

For the ERD diagrams we use Helvetica. Ubuntu Linux does not have Helvetica.

If I rebuild the docs on my laptop explicitly telling the ERD drawing tool to use a font I have (DejaVu Serif) then view them on my laptop, it comes out fine.

The thing that is puzzling me is that as far as I can tell, ReadTheDocs servers don't have Helvetica installed either. So I'm not sure how it comes out ok for some viewers? Luck of what font it does pick?

Helvetica is the default choice of the tool we forked and hacked on, so I don't think it was a conscious choice. I think that means we should feel free to choose something else here.

**Comment by odscjames** [comment]
Final part of this: http://docs.openreferral.org/en/latest/hsds/logical_model/

* Currently on computers that don't have the Lato font installed, it's shown in a system font with maybe odd spacing
* On computers with the Lato font, it is shown fine

On all computers, clicking through to the full diagram works fine.

(This problem is because the Lato font is referenced as an external font in the SVG. This does not work with img tags - so doesn't work on the page - but does work when viewing the SVG directly)
