### ISSUE TITLE
datapackage.json - eligibility - eligibility or description column has gone?

### ISSUE THREAD

**Issue by ghost** [openreferral/specification#267]
http://docs.openreferral.org/en/1.1.1/hsds/reference/#eligibility has a "eligibility" column. (v1.1.1)

http://docs.openreferral.org/en/latest/hsds/reference/#eligibility does not. (all v2's and latest)

**Comment by MikeThacker1** [comment]
Actually the text on [Applying a taxonomy term to an object](http://docs.openreferral.org/en/latest/hsds/classifications/#applying-a-taxonomy-term-to-an-object) helps a lot. (Although it raises more questions on taxonomies for me.)

**Comment by Cskyleryoung** [comment]
I agree with @MikeThacker1, this makes sense, but also raises some questions about the nature of taxonomies. Coming from the 211 space, I naturally want to reserve `taxonomy_term` for taxonomies with official specifications, like AIRS or even Open Eligibility. However, I'm going to also end up putting every defined list of enums from my client's data management system, plus a few pools of thousands of random text strings, in there because I have nowhere else to put them.

**Comment by mrshll1001** [comment]
I think this can be closed, as HSDS 3.0 is out now. datapackage.json has a field called "eligibility_description". The attribute schema does not though, and `other_attribute` seems to have been removed.
