### ISSUE TITLE
Swagger API specifications show "regular_schedule" and "holiday_schedule" but no flag exists on schedule table to indicate regular or holiday

### ISSUE THREAD

**Issue by benjamin-wunder** [openreferral/specification#292]
The /locations/complete endpoint shows "regular_schedule" and "holiday_schedule", as does the "/services/complete" endpoint.

The schema, however, does not have a flag for "regular" or "holiday".

How are these determined in the API reference?

**Comment by greggish** [comment]
The HSD API protocols actually reflect the HSDS 1.2 schema. HSDS 2.0
adopted RRULE conventions instead of those elements; we have not yet
developed an HSDA 2.0, although that is on our roadmap for the next quarter.

**Comment by mrshll1001** [comment]
I am provisionally closing this because we don't have a `/locations` endpoint in the HSDS API Reference as of version 3.0, and therefore this issue no longer applies.

If we want to discuss scoping/adding a `/locations` endpoint to the API Specification, I think that can be done in a new ticket rather than expand the scope of this.
