### ISSUE TITLE
Bullets not rendering on readthedocs

### ISSUE THREAD

**Issue by lgs85** [openreferral/specification#315]
Bullet points are not rendering on readthedocs on the 3.0-dev branch. See for example [here](http://docs.openreferral.org/en/3.0-dev/hsds/use_cases.html). This occurs for me on multiple browsers, but looks fine when I build the docs site locally. No problems on the master branch.

@radix0000 is this something that could have occurred as a result of the recent updates/something you'd be able to take a look at?

**Comment by lgs85** [comment]
Looks as though this [could be docutils related](https://stackoverflow.com/questions/67542699/readthedocs-sphinx-not-rendering-bullet-list-from-rst-file)

**Comment by radix0000** [comment]
It doesn't seem like it is directly related to the recent package upgrades (docutils etc.), though that may have exposed the problem. Seems like the use of the deprecated _html_context_ option in conf.py is the root cause. I will knock up a PR that replaces it with _html_css_files_, which seems do the trick.

**Comment by lgs85** [comment]
Thanks @radix0000 #325 has solved it. Closing as completed.
