### ISSUE TITLE
Link between location and contact?

### ISSUE THREAD

**Issue by pmackay** [openreferral/specification#80]
In the "logical landscape" diagram there is a link between location and contact. However in the spec https://github.com/codeforamerica/OpenReferral/blob/master/Human%20Services%20Data%20Specification%20%20v1.0.md#model I cannot see a reference in either location or contact to point to the other. Should there be a connection between those or not?

**Comment by timgdavies** [comment]
Is there a use-case for this connection? 

I'm tagging this for consideration under 1.1 process - however, unless there is a use-case put forward that needs contact and location connected, then I suggest this is not included.

**Comment by pmackay** [comment]
I posted this more because the diagram and spec were inconsistent rather than a suggestion that there should be a connection. 

However, are there locations that offer services where each location might have a specific contact? Is that possible to define without such a link?

**Comment by timgdavies** [comment]
Checking the current [contact table](http://docs.openreferral.org/en/latest/reference/#contact) this only allows a link between contact and service, contact and organisation, and (if the assumption in #121 holds), between services from a given organisation. 

As you mention, I think there could be a case to link to location so that there are specific contact details for 'organisation at location' or 'service at location'. 

This would involve adding ```location_id``` to the ```contact.csv``` table. 

This would match the behaviour for [phone numbers](http://docs.openreferral.org/en/latest/reference/#phone).

**Comment by klambacher** [comment]
I would like to see contacts tied to Service@Location, or at least the option. It's not uncommon for the service contact to be specific to one location, and inaccurate to rely on a "Location" contact to meet this need if they deal only with the specific Service.

**Comment by NeilMcKechnie** [comment]
I agree with @klambacher . I also know in our client base there are location-specific contacts who are valid for any/all services there so, at the risk of making this too spaghetti-like, suggest we do allow for that linkage too.

**Comment by timgdavies** [comment]
This is in place in 1.1.
