### ISSUE TITLE
Timezone for holiday_schedules.opens_at and holiday_schedules.closes_at

### ISSUE THREAD

**Issue by MaxWhitney** [openreferral/specification#91]
The timezone of the opens_at and closes_at fields in the holiday_schedules table is non-obvious. Kindly determine whether these values should be stored in universal time, with a field for converting back to the appropriate local timezone (preferred) or in the local timezone of the physical location. Then, also please, be sure to document this choice in the specification.

**Comment by timgdavies** [comment]
Interesting issue. 

Looking at the schema, the suggested ```opens_at``` and ```closes_at``` fields are flagged as ```time``` for the data type. 

I'm not sure what this validates as in datapackage, but assuming it follows the XML Schema Definitions (http://www.w3schools.com/xml/schema_dtypes_date.asp) and so **allows** inclusion of an explicit timezone via offset, or including Z for UTC. 

There is a question of whether the schema should then **require** inclusion of the timezone. 

In AirTable version, we might want to switch to having a text column, and then hacking in some validation with an extra formula column

**Comment by timgdavies** [comment]
Tagging this for documentation in 1.0 that we make clear that timestamps should include timezone.

**Comment by klambacher** [comment]
My opinion is that time zone data should be optionally included using the UTC time zone designator (UTC or local time with offset). This is less work to output and process vs. an explicit time zone field.

**Comment by dsantuc** [comment]
The problem with this is that a UTC offset is *not* a time zone. For most localities, UTC offsets change twice a year for daylight savings and whether and when they do varies with the locality (e.g. Arizona doesn't observe DST).

I don't see, given the current spec, how one can reliably answer a question like "Is service/location x open now?"

I think the thing to do would be to get rid of the timezone offset in the time fields and add a timezone field to the organization and location tables, maybe using the identifiers from the [IANA timezone database](https://www.iana.org/time-zones) (e.g. "America/New_York"), since there's support for it in a lot of [programming languages](https://en.wikipedia.org/wiki/Tz_database#Use_in_software_systems). Then the "opens_at" and "closes_at" fields can be interpreted in the timezone for the associated location or service.

**Comment by timgdavies** [comment]
@dsantuc This is a good point. Re-opening the issue. 

Will be interested to hear from other implementers working across timezones how they currently handle this? Do you record timezone info in your database at present?
